name: "Immich public proxy"
description: "Homeassistant addon that wraps an Immich public proxy"
version: "1.0.12"
slug: "immich_public_proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3000/tcp: 8085
schema:
  immich_url: str
options:
  immich_url: "https://internal-immich-url"
environment:
  IMMICH_URL: {immich_url}
